# Generated by Django 2.1.4 on 2018-12-24 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('summary', models.TextField(default='请输入文章摘要....', max_length=300, verbose_name='摘要')),
                ('body', models.TextField(default='请输入文章内容....', verbose_name='内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('slug', models.SlugField(default='slug_input_default(请修改)', max_length=20, unique=True, verbose_name='唯一标识')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('slug', models.SlugField(default='cata_slug_default(请修改)', unique=True, verbose_name='唯一标识')),
                ('disc', models.TextField(default='请输入该分类的介绍....', max_length=300, verbose_name='分类介绍')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Catalogue', verbose_name='文章分类'),
        ),
    ]
