# Generated by Django 2.1.4 on 2019-07-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181225_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test2', models.DateField(verbose_name='日期')),
                ('test3', models.DateTimeField(verbose_name='时间日期')),
                ('test4', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='十进制小数')),
                ('test5', models.FloatField(verbose_name='浮点数')),
                ('test6', models.IntegerField(verbose_name='整形')),
                ('test7', models.BigIntegerField(verbose_name='长整形')),
                ('test8', models.SmallIntegerField(verbose_name='Small INT')),
                ('test9', models.PositiveIntegerField(verbose_name='正数INT')),
                ('test10', models.PositiveSmallIntegerField(verbose_name='正数Small INT')),
                ('test12', models.GenericIPAddressField(verbose_name='IP地址')),
                ('test13', models.SlugField(verbose_name='Slug')),
                ('test14', models.TextField(verbose_name='文本框')),
                ('test15', models.TimeField(verbose_name='时间')),
                ('test16', models.URLField(verbose_name='URL地址')),
                ('test17', models.BinaryField(verbose_name='二进制')),
                ('test18', models.ImageField(upload_to='', verbose_name='图片')),
                ('test19', models.FileField(upload_to='', verbose_name='文件')),
            ],
            options={
                'verbose_name': '测试Model',
                'verbose_name_plural': '测试Model',
            },
        ),
    ]
