# Generated by Django 2.1.4 on 2019-07-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类名称，最多20个字符。', max_length=20, unique=True, verbose_name='分类名称')),
                ('summary', models.CharField(help_text='垃圾分类介绍。最多255字符', max_length=255, verbose_name='分类介绍')),
            ],
            options={
                'verbose_name': '垃圾分类',
                'verbose_name_plural': '垃圾分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubbish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='垃圾名称，最多20个字符。', max_length=20, unique=True, verbose_name='垃圾名称')),
                ('category', models.ForeignKey(help_text='选择垃圾的分类', on_delete=django.db.models.deletion.CASCADE, to='apis.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '垃圾',
                'verbose_name_plural': '垃圾',
                'ordering': ['name'],
            },
        ),
    ]
